version: "3.8"

services:
  db:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=crud
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend
      
  api:
    container_name: inventory-api
    build:
      context: .
      dockerfile: ./server/Dockerfile
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "server"]
    links:
      - db
    ports:
      - 4000:4000
    networks:
      - backend

volumes:
  db:

networks:
  backend:
    driver: bridge



  
