version: "3.8"

services:
  database:
    container_name: database
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=crud
    networks:
      - backend
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      
  server:
    container_name: inventory_api
    image: golang:1.18.0 
    build:
      context: .
      dockerfile: dockerfile
    networks:
      - backend
    ports:
      - 4000:4000

volumes:
  db:

networks:
  backend:
    # Use a custom driver 
    driver: bridge
  
  
